Project_Shoe_Stock/Controllers/GroupingsController.cs
using Project_Shoe_Stock.Models;
using Project_Shoe_Stock.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Project_Shoe_Stock.Controllers
{
    public class GroupingsController : Controller
    {
        private readonly ShoeDbContext db = new ShoeDbContext();
        // GET: Groupings
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GroupingByName()
        {
            var data = db.Stocks.Include(x=>x.Shoe).ToList()
            .GroupBy(s => s.Shoe.Name)
               .Select(g => new GroupData { Key = g.Key, Data = g.Select(x => x) })
               .ToList();
            return View(data);
        }
        public ActionResult GroupingBySize()
        {
            var data = db.Stocks
                .ToList()
               .GroupBy(s => s.Size)
               .Select(g => new GroupData { Key = g.Key.ToString(), Data = g.Select(x => x) })
               .ToList();
            return View(data);
        }
    }
}

Project_Shoe_Stock/Controllers/ShoeModelsController.cs
using Project_Shoe_Stock.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Management;
using System.Web.Mvc;
using X.PagedList;

namespace Project_Shoe_Stock.Controllers
{
    public class ShoeModelsController : Controller
    {
        private readonly ShoeDbContext db = new ShoeDbContext();
        // GET: ShoeModels
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(ShoeModel model)
        {
            if(ModelState.IsValid)
            {
                db.ShoeModels.Add(model);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            var data = db.ShoeModels.FirstOrDefault(x=> x.ShoeModelId == id);
            if(data == null) return new HttpNotFoundResult();
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(ShoeModel model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public PartialViewResult ModelsTable(int pg=1)
        {
            var data = db.ShoeModels.OrderBy(x => x.ShoeModelId).ToPagedList(pg, 5);
            return PartialView("_ShoeModels", data);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var data=db.ShoeModels.FirstOrDefault(x=>x.ShoeModelId==id);
            if (data == null) return new HttpNotFoundResult();
            db.ShoeModels.Remove(data);
            db.SaveChanges();
            return Json(new {success=true});
        }
    }
}

Project_Shoe_Stock/Views/Shared/_Fail.cshtml
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> Failed to save data.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

Project_Shoe_Stock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>
        body {
            padding-top: 70px;
        }

        .main {
            min-height: calc(100vh - 110px);
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>


    <navbar class="navbar bg-light  navbar-expand-md fixed-top shadow-sm px-2">
        <div class="container-fluid">
            <span class="navbar-brand">Shoe Stock</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nv" aria-controls="nv" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse" id="nv">
                <ul class="navbar-nav">
                    <li class="nav-item ">
                        @*<a class="nav-link active" aria-current="page" href="#">Home</a>*@
                        @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Brands", "Index", "Brands", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Models", "Index", "ShoeModels", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Shoes", "Index", "Shoes", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Aggreates", "Index", "Aggreates", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Grouping By shoe", "GroupingByName", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Grouping By size", "GroupingBySize", "Groupings", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">

                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
            </div>

        </div>
    </navbar>
    <main class="container-fluid main">
        @RenderBody()
    </main>
    <footer class="container-fluid">
        &copy; @DateTime.Today.Year
    </footer>
    @RenderSection("scripts", false)
</body>
</html>

Project_Shoe_Stock/Views/Shared/_Success.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> Data saved.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>