Project_Shoe_Stock/Controllers/ShoesController.cs
using Project_Shoe_Stock.Models;
using Project_Shoe_Stock.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
using System.Data.Entity;
using Microsoft.Owin.Security.Provider;
using System.Threading;

namespace Project_Shoe_Stock.Controllers
{
    [Authorize(Roles = "Admin, Members")]
    public class ShoesController : Controller
    {
        private readonly ShoeDbContext db = new ShoeDbContext();
        // GET: Shoes
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ShoeTable(int pg = 1)
        {
            //var data = db.Shoes.OrderBy(x => x.ShoeId).ToPagedList(pg, 5);//lazy loading
            var data = db.Shoes
                .Include(x => x.Stocks)
                .Include(x=> x.ShoeModel)
                .Include(x=> x.Brand)
                .OrderBy(x => x.ShoeId)
                .ToPagedList(pg, 5);
            Thread.Sleep(1000);
            return PartialView("_ShoeTable", data);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            
            return View();
        }
        public ActionResult CreateForm() {
            ShoeInputModel model = new ShoeInputModel();
            model.Stocks.Add(new Stock());
            ViewBag.ShoeModels = db.ShoeModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return PartialView("_CreateForm", model);
        }

        [HttpPost]
        public ActionResult Create(ShoeInputModel model, string act = "")
        {
            if (act == "add")
            {
                model.Stocks.Add(new Stock());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Stocks.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "insert")
            {
                if (ModelState.IsValid)
                {
                    var shoe = new Shoe
                    {
                        BrandId = model.BrandId,
                        ShoeModelId = model.ShoeModelId,
                        Name = model.Name,
                        FirstIntroducedOn = model.FirstIntroducedOn,
                        OnSale = model.OnSale
                    };
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Pictures"), f);
                    model.Picture.SaveAs(savePath);
                    shoe.Picture = f;
                    
                    db.Shoes.Add(shoe);
                    db.SaveChanges();
                    foreach (var s in model.Stocks)
                    {
                        db.Database.ExecuteSqlCommand($@"EXEC InsertStock {(int)s.Size}, {s.Price}, {s.Quantity}, {shoe.ShoeId}");
                    }
                    ShoeInputModel newmodel = new ShoeInputModel() { Name="", FirstIntroducedOn=DateTime.Today};
                    newmodel.Stocks.Add(new Stock());
                    ViewBag.ShoeModels = db.ShoeModels.ToList();
                    ViewBag.Brands = db.Brands.ToList();
                    foreach (var e in ModelState.Values)
                    {
                        
                        e.Value = null;
                    }
                    return View("_CreateForm", newmodel); 
                }
            }
            ViewBag.ShoeModels = db.ShoeModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            return View("_CreateForm", model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Edit( int id)
        {
           
            ViewBag.Id = id;
            return View();
        }
        public ActionResult EditForm(int id)
        {
            var data = db.Shoes.FirstOrDefault(x => x.ShoeId == id);
            if (data == null) return new HttpNotFoundResult();
            db.Entry(data).Collection(x => x.Stocks).Load();
            ShoeEditModel model = new ShoeEditModel
            {
                ShoeId = id,
                BrandId = data.BrandId,
                ShoeModelId = data.ShoeModelId,
                Name = data.Name,
                FirstIntroducedOn = data.FirstIntroducedOn,
                OnSale = data.OnSale,
                Stocks=data.Stocks.ToList()
            };
            ViewBag.ShoeModels = db.ShoeModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.CurrentPic = data.Picture;
            return PartialView("_EditForm", model);
        }

        [HttpPost]
        public ActionResult Edit(ShoeEditModel model, string act = "")
        {
            if (act == "add")
            {
                model.Stocks.Add(new Stock());
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act.StartsWith("remove"))
            {
                int index = int.Parse(act.Substring(act.IndexOf("_") + 1));
                model.Stocks.RemoveAt(index);
                foreach (var e in ModelState.Values)
                {
                    e.Errors.Clear();
                    e.Value = null;
                }
            }
            if (act == "update")
            {
                if (ModelState.IsValid)
                {
                    var shoe = db.Shoes.FirstOrDefault(x => x.ShoeId == model.ShoeId);
                    if(shoe == null) { return new HttpNotFoundResult(); }
                    shoe.Name = model.Name;
                    shoe.FirstIntroducedOn  = model.FirstIntroducedOn;
                    shoe.OnSale = model.OnSale;
                    shoe.BrandId    = model.BrandId;
                    shoe.ShoeModelId = model.ShoeModelId;
                    if(model.Picture != null)
                    {
                        string ext = Path.GetExtension(model.Picture.FileName);
                        string f = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                        string savePath = Path.Combine(Server.MapPath("~/Pictures"), f);
                        model.Picture.SaveAs(savePath);
                        shoe.Picture = f;
                    }
                    
                    db.SaveChanges();
                    db.Database.ExecuteSqlCommand($"EXEC DeleteStockByShoeId {shoe.ShoeId}");
                    foreach (var s in model.Stocks)
                    {
                        db.Database.ExecuteSqlCommand($"EXEC InsertStock {(int)s.Size}, {s.Price}, {s.Quantity}, {shoe.ShoeId}");
                    }

                    
                }
            }
            ViewBag.ShoeModels = db.ShoeModels.ToList();
            ViewBag.Brands = db.Brands.ToList();
            ViewBag.CurrentPic = db.Shoes.FirstOrDefault(x=> x.ShoeId == model.ShoeId)?.Picture;
            return View("_EditForm", model);
        }
        public ActionResult CeateStock()
        {
            var model = new Stock();
            ViewBag.Shoes = db.Shoes.ToList();
            return View(model);
        }
        [HttpPost]
        public ActionResult CeateStock(Stock model)
        {

            if (ModelState.IsValid)
            {
                var stock = new Stock
                {
                    ShoeId = model.ShoeId,
                    Size = model.Size,
                    Price = model.Price,
                    Quantity = model.Quantity,
                };
                db.Stocks.Add(stock);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
            ViewBag.Shoes = db.Shoes.ToList();
            return View(model);
        }
        [HttpPost]
        
        public ActionResult Delete(int id)
        {
            var shoe = db.Shoes.FirstOrDefault(x => x.ShoeId == id);
            if (shoe == null) return new HttpNotFoundResult();
            db.Stocks.RemoveRange(shoe.Stocks.ToList());
            db.Shoes.Remove(shoe);
            db.SaveChanges();
            return Json(new { success = true });
        }
        [HttpPost]
        public ActionResult StDelete(int id)
        {
            var stock = db.Stocks.FirstOrDefault(x => x.StockId == id);
            if (stock == null) return new HttpNotFoundResult();
            db.Stocks.Remove(stock);
            db.SaveChanges();
            return Json(new { success = true });
        }
        public ActionResult StocKEdit(int id)
        {
            var data = db.Stocks.FirstOrDefault(x => x.StockId == id);
            if (data == null) return new HttpNotFoundResult();
            ViewBag.Shoes = db.Shoes.ToList();
            return View(data);
        }
        [HttpPost]
        public ActionResult StocKEdit(Stock model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
           
    }
}

Project_Shoe_Stock/Views/Shoes/CeateStock.cshtml
@model Project_Shoe_Stock.Models.Stock
@{
    ViewBag.Title = "CeateStock";
}


<h2>CeateStock</h2>
<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("CeateStock", "Shoes", FormMethod.Post))
        {

            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.ShoeId, new { @class = "col-from-label col-2 text-end" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.ShoeId, new SelectList(ViewBag.Shoes, "ShoeId", "Name"), "Select model", new { @class = "form-select" })
                    @Html.ValidationMessageFor(x => x.ShoeId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Size, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.EnumDropDownListFor(x => x.Size, new { @class = "form-select" })
                    @Html.ValidationMessageFor(x => x.Size, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Quantity, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Price, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div>
                <button type="submit" name="act" value="add" class="btn btn-info">save</button>

            </div>
        }
    </div>
</div>

Project_Shoe_Stock/Views/Shoes/Index.cshtml
@model IEnumerable<Project_Shoe_Stock.Models.Shoe>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <div class="d-flex justify-content-end mb-1">
            @*@Html.ActionLink(".", "Create", "Shoes", new { }, new { @class = "btn btn-primary btn-sm bi bi-plus-circle" })*@
            <a class="btn btn-primary btn-sm" href="@Url.Action("Create","Shoes")"><i class="bi bi-plus-circle"></i> Add</a>
        </div>
        <div class="spinner-border text-primary" role="status" id="spinner" style="display:none">
            <span class="visually-hidden">Loading...</span>
        </div>
        <div id="table-div">
            @Html.Action("ShoeTable")
        </div>
    </div>

</div>
@section styles
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
}
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(document).on("click", "button.show", function () {
            var showBtn = $(this);
            var hideBtn = showBtn.next();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.hide();
            hideBtn.show();
            trSt.show();
        });
        $(document).on("click", "button.hide", function () {
            var hideBtn = $(this);
            var showBtn = hideBtn.prev();
            var trSh = showBtn.closest("tr");
            var trSt = trSh.next();
            showBtn.show();
            hideBtn.hide();
            trSt.hide();
        });
        $(document).on("click", ".del", function () {
            var id = $(this).data("pk");
            var trP = $(this).closest('tr');
            var trS = trP.next();
            if (confirm("Are you sure to delete?")) {
                $.ajax({
                    url: "/Shoes/Delete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trP.remove();
                            trS.remove();
                        }
                    }
                })
            }
        });
        $(document).on("click", ".dels", function () {
            var id = $(this).data("pk");
            var trP = $(this).closest('tr');
            var trS = trP.next();
            if (confirm("Are you sure to delete?")) {
                $.ajax({
                    url: "/Shoes/StDelete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trP.remove();
                            trS.remove();
                        }
                    }
                })
            }
        });
    
    </script>
}

Project_Shoe_Stock/Views/Shoes/StocKEdit.cshtml
@model Project_Shoe_Stock.Models.Stock
@{
    ViewBag.Title = "StocKEdit";
}

<h2>StocKEdit</h2>
<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("StockEdit", "Shoes", FormMethod.Post))
        {
            @Html.HiddenFor(x=>x.StockId)

            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.ShoeId, new { @class = "col-from-label col-2 text-end" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.ShoeId, new SelectList(ViewBag.Shoes, "ShoeId", "Name"), "Select model", new { @class = "form-select" })
                    @Html.ValidationMessageFor(x => x.ShoeId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Size, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.EnumDropDownListFor(x => x.Size, new { @class = "form-select" })
                    @Html.ValidationMessageFor(x => x.Size, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Quantity, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Quantity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.Price, new { @class = "col-form-lable col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <button type="submit" name="act" value="add" class="btn btn-info">save</button>
        }
    </div>
</div>

Project_Shoe_Stock/Views/Shoes/_CreateForm.cshtml
@model Project_Shoe_Stock.ViewModels.ShoeInputModel
@using (Ajax.BeginForm("Create",
    "Shoes", new { },
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "form-div",
        OnSuccess = "onSuccess"
    },
    new { id = "frm", enctype = "multipart/form-data" }))
{
    <h3>Create new shoe</h3>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BrandId, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.BrandId, new SelectList(ViewBag.Brands, "BrandId", "BrandName"), "Select brand", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.BrandId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.ShoeModelId, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.ShoeModelId, new SelectList(ViewBag.ShoeModels, "ShoeModelId", "ModelName"), "Select model", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.ShoeModelId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Name, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.FirstIntroducedOn, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.FirstIntroducedOn, new { @class = "form-control", type = "date", @Value = DateTime.Today.ToString("yyyy-MM-dd") })
            @Html.ValidationMessageFor(x => x.FirstIntroducedOn, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(x => x.OnSale)
                <label class="form-check-label">
                    On Sale?
                </label>
            </div>
        </div>

    </div>
    <div class="form-group row">
        <div class="col-4 offset-2">
            <div class="d-flex justify-content-between">
                <h4>Stocks</h4>
                <button class="btn btn-sm" type="submit" name="act" value="add" formnovalidate>+</button>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Size</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.Stocks.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(x => Model.Stocks[i].Size, new { @class = "form-select" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Size, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Price, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Quantity, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm " formnovalidate>remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" name="act" value="insert" class="btn btn-primary">Save</button>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back To the List", "Index", "shoes", new {@class="btn btn-primary"})
</div>

Project_Shoe_Stock/Views/Shoes/_EditForm.cshtml
@model Project_Shoe_Stock.ViewModels.ShoeEditModel
@using (Ajax.BeginForm("Edit",
    "Shoes", new { },
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "form-div"
       
    },
    new { id = "frm", enctype = "multipart/form-data" }))
{
    <h3>Edit shoe</h3>
    @Html.HiddenFor(x=> x.ShoeId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.BrandId, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.BrandId, new SelectList(ViewBag.Brands, "BrandId", "BrandName"), "Select brand", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.BrandId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.ShoeModelId, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.DropDownListFor(x => x.ShoeModelId, new SelectList(ViewBag.ShoeModels, "ShoeModelId", "ModelName"), "Select model", new { @class = "form-select" })
            @Html.ValidationMessageFor(x => x.ShoeModelId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Name, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.FirstIntroducedOn, new { @class = "col-from-label col-2 text-end" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.FirstIntroducedOn, new { @class = "form-control", type = "date", @Value = DateTime.Today.ToString("yyyy-MM-dd") })
            @Html.ValidationMessageFor(x => x.FirstIntroducedOn, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Picture, new { @class = "col-from-label col-2 text-end" })
        <div class="col-3">
            @Html.TextBoxFor(x => x.Picture, new { @class = "form-control", type = "file" })
            @Html.ValidationMessageFor(x => x.Picture, "", new { @class = "text-danger" })
        </div>
        <div class="col-1">
            <img src="~/Pictures/@ViewBag.CurrentPic" style="width:35px" class="img-thumbnail" />
        </div>
    </div>
    <div class="form-group row mb-1">
        <div class="col-4 offset-2">
            <div class="form-check">
                @Html.CheckBoxFor(x => x.OnSale)
                <label class="form-check-label">
                    On Sale?
                </label>
            </div>
        </div>

    </div>
    <div class="form-group row">
        <div class="col-4 offset-2">
            <div class="d-flex justify-content-between">
                <h4>Stocks</h4>
                <button class="btn btn-sm" type="submit" name="act" value="add" formnovalidate>+</button>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Size</th>
                        <th>Price</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @for (var i = 0; i < Model.Stocks.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.EnumDropDownListFor(x => Model.Stocks[i].Size, new { @class = "form-select" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Size, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Price, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                @Html.TextBoxFor(x => Model.Stocks[i].Quantity, new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.Stocks[i].Quantity, "", new { @class = "text-danger" })
                            </td>
                            <td>
                                <button name="act" value="remove_@i" type="submit" class="btn btn-danger btn-sm" formnovalidate>Remove</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" name="act" value="update" class="btn btn-primary">Save</button>
        </div>
    </div>
}

Project_Shoe_Stock/Views/Shoes/_ShoeTable.cshtml
@model IEnumerable<Project_Shoe_Stock.Models.Shoe>
@using X.PagedList
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common
<h3 class="text-center text-decoration-underline text-danger">Shoe's Details </h3>
<table class="table table-hover">
    <thead>
        <tr>
            <th></th>
            <th></th>
            <th>Brand</th>
            <th>Model</th>
            <th>Name</th>
            <th>First Introduced</th>
            <th>On Sale?</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td style="width:40px;text-align:center">
                    <button class="btn btn-sm show"><i class="bi bi-chevron-right"></i></button>
                    <button class="btn btn-sm hide" style="display:none"><i class="bi bi-chevron-up"></i></button>
                </td>
                <td style="width:45px;text-align:center"><img src="~/Pictures/@s.Picture" class="rounded-circle" style="width:40px" /></td>
                <td>@s.Brand.BrandName</td>
                <td>@s.ShoeModel.ModelName</td>
                <td>@s.Name</td>
                <td>@s.FirstIntroducedOn.ToString("yyyy-MM-dd")</td>
                <td>@(s.OnSale ? "Yes": "No")</td>
                <td>
                    <a class="btn btn-info btn-sm" href="@Url.Action("Edit","Shoes",new { id = s.ShoeId })"><i class="bi bi-pencil-square"></i></a>
                    @*@Html.ActionLink("Edit", "Edit", "Shoes", new { id = s.ShoeId }, new { @class = "btn btn-primary btn-sm bi bi-pencil-square" })*@
                    <button data-pk="@s.ShoeId" class="btn btn-danger btn-sm del"><i class="bi bi-trash"></i></button>
                </td>
            </tr>
            <tr style="display:none">
                <td></td>
                <td colspan="6">
                    <div class="d-flex justify-content-between">
                        <h4>Stocks</h4>
                        @*@Html.ActionLink("Create", "CeateStock", "Shoes", new { id = s.ShoeId }, new { @class = "btn bi bi-plus-circle" })*@
                        <a class="btn btn-info" href="@Url.Action("CeateStock","Shoes")"><i class="bi bi-plus-circle"></i></a>
                    </div>
                    <table class="table table-bordered table-dark table-striped">
                        <thead>
                            <tr>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var t in s.Stocks)
                            {
                                <tr>
                                    <td>@t.Size</td>
                                    <td>@t.Price.ToString("0.00")</td>
                                    <td>@t.Quantity</td>
                                    <td>
                                        @*@Html.ActionLink("Edit", "StocKEdit", "Shoes", new { id = t.StockId }, new { @class = "btn btn-info" })*@
                                        <a class="btn btn-primary btn-sm" href="@Url.Action("StocKEdit","Shoes",new { id = t.StockId })"><i class="bi bi-pencil-square"></i></a>

                                        <button data-pk="@t.StockId" class="btn btn-danger btn-sm dels"><i class="bi bi-trash"></i></button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="d-flex justify-content-end">

    @Html.PagedListPager((IPagedList)Model, pg => Url.Action("ShoeTable", "Shoes", new { pg = pg }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
    {
        UlElementClasses = new string[] { "pagination", "pagination-sm" },
        LiElementClasses = new string[] { "page-item" },
        PageClasses = new string[] { "page-link" },
        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
        DisplayLinkToNextPage = PagedListDisplayMode.Always
    },
    new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "table-div", LoadingElementId="spinner" }))
</div>