Project_Shoe_Stock/Controllers/BrandsController.cs
using Project_Shoe_Stock.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;

namespace Project_Shoe_Stock.Controllers
{
    public class BrandsController : Controller
    {
        protected readonly ShoeDbContext db = new ShoeDbContext();
       
        // GET: Brands
        public ActionResult Index()
        {
            var data = db.Brands.ToList();
            db.Shoes.Add(new Shoe());
            return View(data);
        }

        public ActionResult Create()
        {
           return View();   
        }
        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            if (ModelState.IsValid)
            {

                db.Brands.Add(brand);
                db.SaveChanges();
                return PartialView("_Success");
            }

            return PartialView("_Fail"); 



        }
        public ActionResult Edit(int id)
        {
            var data = db.Brands.FirstOrDefault(x => x.BrandId == id);
            if (data == null) return new HttpNotFoundResult();
            return View(data);
        }
        [HttpPost]
        public ActionResult Edit(Brand model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");

        }
        [HttpPost]

        public ActionResult Delete(int id)
        {
            var brand = db.Brands.FirstOrDefault(x => x.BrandId == id);
            if (brand == null) return new HttpNotFoundResult();

            db.Brands.Remove(brand);
            db.SaveChanges();
            return Json(new { success = true });
        }
    }
}

Project_Shoe_Stock/Views/Brands/Create.cshtml
@model Project_Shoe_Stock.Models.Brand
@{
    ViewBag.Title = "Create";
}


<div class="row">
    <div class="col-12">
        <div id="msg">

        </div>
        @using (Ajax.BeginForm("Create", "Brands", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg", OnSuccess = "onSuccess" }, new { id = "frm" }))
        {
            <h3>Create new Brand</h3>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.BrandName, new { @class = "col-form-label col-2 text-end" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.BrandName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.BrandName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
    <div>
        @Html.ActionLink("Back to the list", "Index")
    </div>


</div>
@section scripts
{
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script>
        function onSuccess() {
            $("#frm").trigger("reset");
        }
    </script>
}

Project_Shoe_Stock/Views/Brands/Edit.cshtml
@model Project_Shoe_Stock.Models.Brand
@{
    ViewBag.Title = "Edit";
}


<div class="row">
    <div class="col-12">
        <div id="msg">

        </div>
        @using (Ajax.BeginForm("Edit", "Brands", new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "msg" }, new { id = "frm" }))
        {
            @Html.HiddenFor(x => x.BrandId)
            <h3>Edit Enlisted Brand</h3>
            <div style="margin-top:20px">
                <div class="form-group row mb-1 offset-3">
                    @Html.LabelFor(x => x.BrandName, new { @class = "col-form-label col-2 text-end" })
                    <div class="col-5">
                        @Html.TextBoxFor(x => x.BrandName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.BrandName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group row mb-1">

                    <div class="col-4 offset-5">
                        <button type="submit" class="btn btn-primary">Save</button>
                       

                    </div>
                </div>
            </div>
        }
    </div>
    <div>
        @Html.ActionLink("Back to the list", "Index")
    </div>
</div>

Project_Shoe_Stock/Views/Brands/Index.cshtml
@model IEnumerable<Project_Shoe_Stock.Models.Brand>
@{
    ViewBag.Title = "Index";
}

<h2 style="text-align:center;color:red;"><u>Brand list</u></h2>
<div class="text-center">
    <h4>To @Html.ActionLink("Create", "Create", "Brands", new{ }, new { @class = "btn btn-primary" }) New Brand</h4>
</div>
<div class="d-flex justify-content-sm-center">
    <div class="col-6">
        <table class="table table-striped">
            <thead >
                <tr>
                    <th>Brand Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    <tr>
                        <td>@b.BrandName</td>
                        <td>
                            <a class="btn btn-info" href="@Url.Action("Edit","Brands",new { id = b.BrandId })"><i class="bi bi-pencil-square"></i></a>
                            
                            <a></a>
                            <button data-pk="@b.BrandId" class="btn btn-danger btn-sm del bi bi-trash"></button>
                        </td>
                    </tr>

                }
            </tbody>
        </table>

    </div>
</div>
@section styles
{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
}
@section scripts {
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script>
        $(".del").click(function () {
            var id = $(this).data("pk");
            var trP = $(this).closest('tr');
            var trS = trP.next();
            if (confirm("Are you sure to delete?\nProduct with sales will be deleted.")) {
                $.ajax({
                    url: "/Brands/Delete/" + id,
                    method: "post",
                    dataType: "json",
                    success: r => {
                        if (r.success == true) {
                            trP.remove();
                            trS.remove();
                        }
                    }
                })
            }
        });
    </script>
}